### ISSUE TITLE
Token refresh not working

### ISSUE THREAD

**Issue by turing-complet** [turing-complet/python-ouraring#13]
Description: even when we supply access,refresh token and expiry time, we get this stack trace, which implies the api didn't return a new token.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\code\python-ouraring\oura\client.py", line 61, in fetch_access_token
    client_secret = self.client_secret)
  File "C:\Users\Admin\.virtualenvs\python-ouraring-D1VesrpD\lib\site-packages\requests_oauthlib\oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Admin\.virtualenvs\python-ouraring-D1VesrpD\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\Admin\.virtualenvs\python-ouraring-D1VesrpD\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Admin\.virtualenvs\python-ouraring-D1VesrpD\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 389, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

Investigating where the bug is..

**Comment by turing-complet** [comment]
fixed #14

**Comment by ethanopp** [comment]
@turing-complet I seem to still be getting this issue... I am writing a script just to pull my own data... So I manually ran the token_request.py script and saved all the values to a config.ini file...

Then in my script I use the following:
```
config = configparser.ConfigParser()
config.read('config.ini')

client_id = config.get('oura', 'client_id')
client_secret = config.get('oura', 'client_secret')
token_dict = ast.literal_eval(config.get('oura', 'token_dict'))

oura = OuraClient(client_id=client_id, client_secret=client_secret, access_token=token_dict['access_token'],
                  refresh_token=token_dict['refresh_token'], refresh_callback=token_dict)
```

It worked yesterday when the token was active, however now when it tries to refresh, the console prints out the following:
```
refrshing manually
[2019-06-04 09:41:52,560] ERROR in datapull: (missing_token) Missing access token parameter.
[2019-06-04 09:41:52,593] ERROR in datapull: 'MissingTokenError' object has no attribute 'translate'
```

Am I doing something wrong?

**Comment by turing-complet** [comment]
@ethanopp hard for me to say without more context, but the refresh_callback should be a function that takes in your token_dict, so that may be related. If you're still having problems after that I will try running through the refresh scenario again.

**Comment by ethanopp** [comment]
@turing-complet where I am getting confused is how the OuraClient() takes the access_token in addition to the refresh_callback.

If the refresh_callback() is the function that is refreshing the access_token, wouldn't we always be passing the old access_token to this object?

**Comment by ethanopp** [comment]
Here's an example of what I'm trying:

```
def refresh_oura_token():
    auth_client = OuraOAuth2Client(client_id=client_id, client_secret=client_secret)
    url = auth_client.authorize_endpoint(scope=["email", "personal", "daily"],
                                         redirect_uri='http://127.0.0.1:8050/oura/authorized')

    # TODO: have browser automatically get the code later, for now manually paste
    print(url)
    auth_code = input('Input code: ')
    ###

    auth_client.fetch_access_token(auth_code)
    return auth_client.session.token

def pull_oura_data():
    new_token = refresh_oura_token()
    print(new_token)

    oura = OuraClient(client_id=client_id, client_secret=client_secret, refresh_callback=new_token)

    print(oura.user_info())
```

And this is the output:
```
('https://cloud.ouraring.com/oauth/authorize?response_type=code&client_id=REDACTED&redirect_uri=http%3A%2F%2F127.0.0.1%3A8050%2Foura%2Fauthorized&scope=email+personal+daily&state=pZvjyHf1IQiZQfLyW1qq9KB5U23JLb', 'pZvjyHf1IQiZQfLyW1qq9KB5U23JLb')

Input code: DJZNLCATUQXTVKWZZZKNWRVFK4TY6O5A

{'token_type': 'bearer', 'expires_in': 86400, 'access_token': 'GFIXGWJ5MUYYHSFR76GZ3BWDC5YMUB4R', 'refresh_token': 'IRJNVCNCASNNQT5HRWF3VZJU23F5BL3D', 'expires_at': 1559828602.366317}

refrshing manually

[2019-06-05 09:43:23,065] ERROR in datapull: (missing_token) Missing access token parameter.
```

**Comment by ethanopp** [comment]
Ahh disregard above... again :) had some minor bugs in other code.

Working fine now!
